### PR TITLE
Restore ApplicationName parameter

### LINKED ISSUE #15: ApplicationName parameter
lines 386-389 have 
```powershell
if ($ApplicationName) {
    $CSBuilder["Application Name"] = $ApplicationName
}
```
but I don't see a parameter defined for $ApplicationName.

Should there be one like this?:

```powershell
[Parameter(Position = 11,
	Mandatory = $false,
	ValueFromPipelineByPropertyName = $true,
	ValueFromRemainingArguments = $false)]
[string]$ApplicationName
```

### PR DESCRIPTION
**Pull request by alevyinroc**
Resolves #15 - ApplicationName parameter got dropped in the midst of some odd merges a long time ago

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Hiyo!

Awesome, thanks, Param bit looks good to me!

Is there a mix of tabs an spaces in here?  Noticed some lines use spaces, some use tabs, and indentation looks a little out of sorts (looks like some of it was there before this PR)

Cheers!

**Comment by alevyinroc** [comment]
You're almost certainly correct. I threw it together really fast & copy/pasted from an older Github (web view) revision. I'll see if I can fix it up some.

**Comment by alevyinroc** [comment]
OK, I see what you're talking about now. I think that's auto-formatting from VSCode using the settings I use for dbatools.

**Comment by RamblingCookieMonster** [comment]
Oh!  Didn't realize this was still out here - You might want to do a quick rebase, or just kill everything, add the help/param, force push to the branch?

**Comment by potatoqualitee** [comment]
closed cuz fixed in #20

**Pull request closed without merging**
